---
configs:
  use: 'dev'              # i think this is the default config behavior namespace match...?
  # stage:
  #   public_ip: 'x.x.x.x'  # interesting can push to xen, or a kvm?
  #   private_ip: 'y.y.y.y'
  #   # more variables
  dev:
    vm_box_type: 'virtualbox'
    arg_user_name: 'ansible'
    arg_user_pass: 'ansible'
    arg_user_uuid: 999999999
    arg_user_desc: "ansible manager, kicking crap onto this box, one deploy at a time..."
    node:
      vagrant_name: 'node_%{hook}'
      vagrant_box: 'centos/7'
      hostname: 'compute.node.%{hook}'
      private_ip: '192.168.34.5%{hook}'
      vbox_name: 'rc_ansible_centos7_node_%{hook}'
      provision_label: 'compute node_%{hook}'
      provision_path: './remote/provision.sh'
    # remote_lb:
    #   vagrant_name: 'remote_lb_node'
    #   vagrant_box: 'centos/7'
    #   hostname: 'remote.lb.node'
    #   private_ip: '192.168.34.51'
    #   vbox_name: 'rc_ansible_remote_lb_centos_7'
    #   provision_label: 'remote_lb node'
    #   provision_path: './remote/provision.sh'
    # remote_db:
    #   vagrant_name: 'remote_db_node'
    #   vagrant_box: 'centos/7'
    #   hostname: 'remote.db.node'
    #   private_ip: '192.168.34.52'
    #   vbox_name: 'rc_ansible_remote_db_centos_7'
    #   provision_label: 'remote_db node'
    #   provision_path: './remote/provision.sh'
    # remote_app1:
    #   vagrant_name: 'remote_app1_node'
    #   vagrant_box: 'centos/7'
    #   hostname: 'remote.app1.node'
    #   private_ip: '192.168.34.53'
    #   vbox_name: 'rc_ansible_remote_app1_centos_7'
    #   provision_label: 'remote_app1 node'
    #   provision_path: './remote/provision.sh'
    # remote_app2:
    #   vagrant_name: 'remote_app2_node'
    #   vagrant_box: 'centos/7'
    #   hostname: 'remote.app2.node'
    #   private_ip: '192.168.34.54'
    #   vbox_name: 'rc_ansible_remote_app2_centos_7'
    #   provision_label: 'remote_app2 node'
    #   provision_path: './remote/provision.sh'
    manage:
      vagrant_name: 'manage_node'
      vagrant_box: 'centos/7'
      hostname: 'manage.node'
      private_ip: '192.168.34.50'
      vbox_name: 'rc_ansible_centos7_manage'
      provision_label: 'manager node'
      provision_path: './manage/provision.sh'

    # more variables
