---
# this is a soft touch ...
# the idea of this soft touch is to just do a 'quick' health check of the 
#   box configuration.  OPTS side... But you can expand this to test the
#   services within the box.  Probably want to put that into another playbook
- hosts: loadbalancer
  become: true
  gather_facts: true
  tasks:
    - name: verify nginx service status
      command: service nginx status
      changed_when: false

    - name: verify nginx listening on port
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify postgresql service status
      command: service postgresql status
      changed_when: false
      
    - name: verify postgresql listening on port
      wait_for: 
        host={{ ansible_eth1.ipv4.address }}
        port=5432 
        timeout=1

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: verify apache2 service status 
      command: service httpd status
      changed_when: false
      
    - name: verify apache2 listening on port
      wait_for: port=80 timeout=1

- hosts: control
  tasks:
    # - debug:
    #     msg: "loadbalancer - {{ item }}"
    #   with_items: "{{ groups.loadbalancer }}"

    - name: "verify end to end reponse"
      uri: 
        url=http://{{ item }}
        return_content=yes
      with_items: "{{ groups.loadbalancer }}"
      register: lb_index
    # this is ...
    # - debug:
    #     msg: "index value - {{ item }}"
    #   with_items: "{{ lb_index.results }}"

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{ lb_index.results }}"

    - name: "verify db reponse"
      uri:
        url=http://{{item}}/db
        return_content=yes
      with_items: "{{ groups.webserver }}"
      register: db_lb_index
    
    - fail: msg="lb-db index failed to return content"
      when: "'Database Connected from ' not in item.content"
      with_items: "{{ db_lb_index.results }}"

- hosts: loadbalancer
  tasks:
    # - debug:
    #     msg: "ansible hostname - {{ item }}"
    #   with_items: "{{ ansible_hostname }}"
    # - debug:
    #     msg: "inventory hostname - {{ item }}"
    #   with_items: "{{ inventory_hostname }}"

    # - debug:
    #     msg: "webserver - {{ item }}"
    #   with_items: "{{ groups.webserver }}"

    - name: "verify backend response"
      uri: 
        url=http://{{ item }}
        return_content=yes
      with_items: "{{ groups.webserver }}"
      register: app_index
    
    # - debug:
    #     msg: "index value: {{ item.item }}"
    #   with_items: "{{ app_index.results }}"

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny ' not in item.content"
      with_items: "{{ app_index.results }}"
    - name: "verify db app reponse"
      uri:
        url=http://{{item}}/db
        return_content=yes
      with_items: "{{ groups.webserver }}"
      register: db_app_index
    
    - fail: msg="lb-db index failed to return content"
      when: "'Database Connected from ' not in item.content"
      with_items: "{{ db_app_index.results }}"
